---
- name: create jenkins init.groovy.d/ workspace
  file: path="{{ jenkins_home }}/init.groovy.d" state=directory owner=www group=www  mode=0755
  ignore_errors: True
  tags: workspace

- name: configure default users
  template:
    src: basic-security.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
  register: jenkins_users_config
